### ISSUE TITLE
Bad URL to the PNG image in the Apple Developer Forum

### ISSUE THREAD

**Issue by quark67** [zjohnzheng/DeveloperAssets#1]
In https://developer.apple.com/forums/thread/649268, you provide a screenshot with the following url: 

https://github.com/zjohnzheng/DeveloperAssets/blob/master/Shot%25202020-06-19%2520at%25201.09.00%2520PM.png
 this give a 404 error page.

The correct url is:

https://github.com/zjohnzheng/DeveloperAssets/blob/master/Shot%202020-06-19%20at%201.09.00%20PM.png

**Comment by zjohnzheng** [comment]
Thanks! I updated the link in the forums.

**Comment by zjohnzheng** [comment]
It seems that the Developer Forums adds a '25' in front of every '%' symbol. Weird.

**Comment by quark67** [comment]
Perhaps you can add a post about the bug in this category: https://developer.apple.com/forums/tags/forums-feedback

**Comment by zjohnzheng** [comment]
I'll post a new question about the bug. Thanks for your help!

**Comment by zjohnzheng** [comment]
[Here](https://developer.apple.com/forums/thread/649436t) is the post!
